### ISSUE TITLE
Pinguino driver

### ISSUE THREAD

**Issue by rblanchot** [MefhigosetH/pinguino-nsi-installer#18]
When I connected a Pinguino (bootloader mode), it was not automatically recognized by Windows so I guess the Installer should also deal with the Driver installation to be complete.

**Comment by MefhigosetH** [comment]
I will be working on this. Perhaps in the meantime the installer let the drivers in a folder like C:\pinguino-ide\drivers for the user does not have to download and unzip these files on your own.

Thanks for your feedback.

**Comment by MefhigosetH** [comment]
Hi @rblanchot :

I'll close this issue and open two other issue. One for the Win 9X/XP and other for Vista/7/8 platform.

This is beacause I need to code two diferents routines for each platform. I succeeded install Pinguino drivers in Windows Vista/7/8, so that it can be recognized automatically the first time it is connected. Now I'll work for update the installer code with this new method.

**Comment by rblanchot** [comment]
Fine ! Good luck.
BTW, did you get the chance to try the Debian packages (I sent you a private message on the Forum about that) ?.

**Comment by MefhigosetH** [comment]
Owa! Sory. I don't receive any notifications on thats PMs... I'll read my inbox now.
